name: Python Package using Conda
on: 
  schedule:
    - cron: "0 1 3 * *"

jobs:
  test:
    name: Test python ${{ matrix.python-version }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          use-only-tar-bz2: true
          miniforge-version: latest
          environment-file: AE.yml
          environment-name: AE
      - name: Install test packages
        shell: bash -l {0}
        run: |
          pip install pytest nbconvert nbformat
      - name: which python
        shell: bash -l {0}
        run: |
          which python
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest .github/workflows/test_AE_notebooks.py
